package app

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

func (a *App) runCompletion(args []string) int {
	if len(args) == 0 || args[0] != "bash" {
		fmt.Fprintln(os.Stderr, "Usage: conctl completion bash")
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "Supported shells: bash")
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "To enable, add to your ~/.bashrc or ~/.bash_profile:")
		fmt.Fprintln(os.Stderr, "  eval \"$(conctl completion bash)\"")
		return ExitUsage
	}

	a.generateBashCompletion(os.Stdout)
	return ExitSuccess
}

func (a *App) generateBashCompletion(w io.Writer) {
	// Collect resource names and built-in commands.
	var resourceNames []string
	for _, r := range a.resources {
		resourceNames = append(resourceNames, r.Name)
	}

	globalFlags := []string{"--url", "--timeout", "--format", "--output", "--verbose"}

	fmt.Fprintln(w, "# bash completion for conctl")
	fmt.Fprintln(w, "# Generated by: conctl completion bash")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# To enable, add to your ~/.bashrc or ~/.bash_profile:")
	fmt.Fprintln(w, "#   eval \"$(conctl completion bash)\"")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "_conctl_completions() {")
	fmt.Fprintln(w, "    local cur prev words cword")
	fmt.Fprintln(w, "    if declare -F _init_completion >/dev/null 2>&1; then")
	fmt.Fprintln(w, "        _init_completion || return")
	fmt.Fprintln(w, "    else")
	fmt.Fprintln(w, "        cur=\"${COMP_WORDS[COMP_CWORD]}\"")
	fmt.Fprintln(w, "        prev=\"${COMP_WORDS[COMP_CWORD-1]}\"")
	fmt.Fprintln(w, "        words=(\"${COMP_WORDS[@]}\")")
	fmt.Fprintln(w, "        cword=$COMP_CWORD")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w)

	// Resource → command mapping.
	fmt.Fprintln(w, "    # Resource and command definitions")
	fmt.Fprintf(w, "    local resources=\"%s\"\n", strings.Join(resourceNames, " "))
	fmt.Fprintf(w, "    local builtins=\"help version completion\"\n")
	fmt.Fprintf(w, "    local global_flags=\"%s\"\n", strings.Join(globalFlags, " "))
	fmt.Fprintln(w)

	// Per-resource command lists.
	for _, r := range a.resources {
		var cmdNames []string
		for _, c := range r.Commands {
			cmdNames = append(cmdNames, c.Name)
		}
		fmt.Fprintf(w, "    local cmds_%s=\"%s\"\n", bashSafe(r.Name), strings.Join(cmdNames, " "))
	}
	fmt.Fprintln(w)

	// Per-resource-command flag lists.
	for _, r := range a.resources {
		for _, c := range r.Commands {
			if c.Flags == nil {
				continue
			}
			var flagNames []string
			fs := c.Flags()
			fs.VisitAll(func(f *flag.Flag) {
				flagNames = append(flagNames, "--"+f.Name)
			})
			if len(flagNames) > 0 {
				fmt.Fprintf(w, "    local flags_%s_%s=\"%s\"\n",
					bashSafe(r.Name), bashSafe(c.Name), strings.Join(flagNames, " "))
			}
		}
	}
	fmt.Fprintln(w)

	// Determine position by scanning words for resource and command.
	fmt.Fprintln(w, "    # Find the resource and command in the current line")
	fmt.Fprintln(w, "    local resource=\"\" command=\"\"")
	fmt.Fprintln(w, "    local i")
	fmt.Fprintln(w, "    for ((i=1; i < cword; i++)); do")
	fmt.Fprintln(w, "        local w=\"${words[i]}\"")
	fmt.Fprintln(w, "        # Skip global flags and their values")
	fmt.Fprintln(w, "        case \"$w\" in")
	fmt.Fprintln(w, "            --url|--timeout|--format|--output)")
	fmt.Fprintln(w, "                ((i++)); continue ;;")
	fmt.Fprintln(w, "            --url=*|--timeout=*|--format=*|--output=*|--verbose)")
	fmt.Fprintln(w, "                continue ;;")
	fmt.Fprintln(w, "        esac")
	fmt.Fprintln(w, "        if [[ -z \"$resource\" ]]; then")
	fmt.Fprintln(w, "            resource=\"$w\"")
	fmt.Fprintln(w, "        elif [[ -z \"$command\" ]]; then")
	fmt.Fprintln(w, "            command=\"$w\"")
	fmt.Fprintln(w, "        fi")
	fmt.Fprintln(w, "    done")
	fmt.Fprintln(w)

	// Value completions for global flags (checked first — applies at any position).
	fmt.Fprintln(w, "    # Complete values for global flags")
	fmt.Fprintln(w, "    case \"$prev\" in")
	fmt.Fprintln(w, "        --format)")
	fmt.Fprintln(w, "            COMPREPLY=($(compgen -W \"json table md jsonl\" -- \"$cur\"))")
	fmt.Fprintln(w, "            return ;;")
	fmt.Fprintln(w, "        --output)")
	fmt.Fprintln(w, "            COMPREPLY=($(compgen -f -- \"$cur\"))")
	fmt.Fprintln(w, "            return ;;")
	fmt.Fprintln(w, "    esac")
	fmt.Fprintln(w)

	// Completion logic.
	fmt.Fprintln(w, "    # Complete based on position")
	fmt.Fprintln(w, "    if [[ -z \"$resource\" ]]; then")
	fmt.Fprintln(w, "        # Completing resource name or global flag")
	fmt.Fprintln(w, "        if [[ \"$cur\" == --* ]]; then")
	fmt.Fprintln(w, "            COMPREPLY=($(compgen -W \"$global_flags\" -- \"$cur\"))")
	fmt.Fprintln(w, "        else")
	fmt.Fprintln(w, "            COMPREPLY=($(compgen -W \"$resources $builtins\" -- \"$cur\"))")
	fmt.Fprintln(w, "        fi")
	fmt.Fprintln(w, "        return")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w)

	fmt.Fprintln(w, "    if [[ -z \"$command\" ]]; then")
	fmt.Fprintln(w, "        # Completing command name within a resource")
	fmt.Fprintf(w, "        local var=\"cmds_${resource//-/_}\"\n")
	fmt.Fprintln(w, "        COMPREPLY=($(compgen -W \"${!var}\" -- \"$cur\"))")
	fmt.Fprintln(w, "        return")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w)

	fmt.Fprintln(w, "    # Completing flags for a specific command")
	fmt.Fprintln(w, "    if [[ \"$cur\" == --* || \"$cur\" == -* || \"$cur\" == \"\" ]]; then")
	fmt.Fprintf(w, "        local var=\"flags_${resource//-/_}_${command//-/_}\"\n")
	fmt.Fprintln(w, "        COMPREPLY=($(compgen -W \"${!var} $global_flags\" -- \"$cur\"))")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "complete -F _conctl_completions conctl")
}

// bashSafe replaces hyphens with underscores for bash variable names.
func bashSafe(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}
