package api

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/alhasaniq/consortium/pkg/workflow"
)

// TestFrontendSubmitPayloadsPassValidation guards the frontend↔backend
// validation contract.
//
// The fixtures in testdata/submit_contract/ are generated by the frontend
// converters (Ensemble buildExecutionRequest, Builder flowToWorkflow) — see
// frontend/src/utils/submitContract.test.ts — and committed verbatim. They are
// the exact `workflow` payloads the frontend POSTs to /api/workflows/submit.
//
// This test runs each through the REAL backend validator. If the backend
// tightens node validation (e.g. a new "no implicit defaults" requirement), the
// frontend converters will not be emitting the new field, these fixtures stop
// validating, and this test fails immediately — instead of every user submit
// silently returning 400 in production. The fix is to update the converters and
// regenerate the fixtures (UPDATE_SUBMIT_CONTRACT=1 bun test).
func TestFrontendSubmitPayloadsPassValidation(t *testing.T) {
	dir := filepath.Join("testdata", "submit_contract")
	files, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		t.Fatalf("glob fixtures: %v", err)
	}
	if len(files) == 0 {
		t.Fatalf("no submit-contract fixtures found in %s — the frontend "+
			"submitContract.test.ts generates these; they must be committed", dir)
	}

	// nil registry: skip model-existence checks (offline), keep every structural
	// / variable / aggregation rule — which is exactly the surface that drifts.
	validator := workflow.NewValidator(nil)

	for _, file := range files {
		t.Run(filepath.Base(file), func(t *testing.T) {
			raw, err := os.ReadFile(file)
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			var wf workflow.Workflow
			if err := json.Unmarshal(raw, &wf); err != nil {
				t.Fatalf("unmarshal fixture: %v", err)
			}

			result := validator.Validate(&wf)
			if !result.Valid {
				t.Errorf("frontend submit payload %s no longer passes backend "+
					"validation — frontend converters are out of sync with the "+
					"validator. Update them and regenerate the fixtures "+
					"(UPDATE_SUBMIT_CONTRACT=1 bun test). Errors:", filepath.Base(file))
				for _, e := range result.Errors {
					t.Errorf("  - node=%s field=%s: %s", e.NodeID, e.Field, e.Message)
				}
			}
		})
	}
}
