#!/bin/bash

set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
PROFILE_RAW="${1-}"
FORCE_WRITE="${FORCE:-0}"

cd "$ROOT_DIR"

if [ -z "$PROFILE_RAW" ]; then
	PROFILE_RAW="$(basename "$ROOT_DIR")"
fi

PROFILE="$(printf '%s' "$PROFILE_RAW" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9._-' '-')"
if [ -z "$PROFILE" ]; then
	PROFILE="default"
fi

ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ] && [ "$FORCE_WRITE" != "1" ]; then
	echo "$ENV_FILE already exists. Re-run with FORCE=1 to overwrite."
	exit 1
fi

# Do not copy .env between worktrees. Provider keys should be supplied through
# the shell, a local .env, or a local .env.local that is never committed.
if [ ! -f .env ]; then
	echo "No .env found. Mock tests and UI work can run without one; real provider-backed runs need OPENROUTER_API_KEY."
fi

SEED="$(printf '%s' "$PROFILE" | cksum | awk '{print $1}')"
OFFSET=$((SEED % 200))
BACKEND_PORT=$((8080 + OFFSET))
FRONTEND_PORT=$((3000 + OFFSET))
DB_PATH="./.local/$PROFILE/consortium.db"

mkdir -p "./.local/$PROFILE"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-worktree-env.sh for local multi-worktree development.
WORKTREE_PROFILE=$PROFILE
PORT=$BACKEND_PORT
BIND_ADDR=127.0.0.1:$BACKEND_PORT
BACKEND_URL=http://localhost:$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
FRONTEND_URL=http://localhost:$FRONTEND_PORT
CONCTL_URL=http://localhost:$BACKEND_PORT
DB_PATH=$DB_PATH
DB_MAX_OPEN_CONNS=4
DB_MAX_IDLE_CONNS=4

# Uncomment locally when this worktree needs real provider-backed runs.
# OPENROUTER_API_KEY=<OPENROUTER_API_KEY>

# Lower local defaults so multiple backend instances can coexist.
MAX_CONCURRENT_WORKFLOWS=25
WORKER_COUNT=50
WORKER_INITIAL_COUNT=5
MAX_PARALLEL_NODES_PER_WORKFLOW=16
EOF

echo "Wrote $ENV_FILE"
echo "  profile:  $PROFILE"
echo "  backend:  http://localhost:$BACKEND_PORT"
echo "  frontend: http://localhost:$FRONTEND_PORT"
echo "  db:       $DB_PATH"
